### Valid login
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}

### Nearby planes
GET http://localhost:8080/opensky/nearby?la=30.00&lo=30.00
