### List of the users
GET http://localhost:8080/user

### Add a correct user
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "email": "user1@visa.com",
  "username": "user1",
  "password": "password1"
}

### Add a blank user
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "email": "",
  "username": "",
  "password": ""
}

### Find a user
GET http://localhost:8080/user/1

### Update a user

PUT http://localhost:8080/user/1
Content-Type: application/json

{
  "email": "username2@visa.com",
  "username": "username2",
  "password": "password123"
}

### Delete a user
DELETE http://localhost:8080/user/1

### Valid login
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}

### Invalid login
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password2"
}

### Logout
POST http://localhost:8080/user/logout